import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { loadYarnLockGraph } from "../../src/parsers/yarn-lock-graph.js";
import { removeDir } from "../test-utils.js";

function writeLock(contents: string): { dir: string; lockPath: string } {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "cve-lite-yarn-graph-"));
  const lockPath = path.join(dir, "yarn.lock");
  fs.writeFileSync(lockPath, contents, "utf8");
  return { dir, lockPath };
}

const CLASSIC = `# yarn lockfile v1


express@^4.17.1:
  version "4.17.1"
  resolved "https://registry.yarnpkg.com/express/-/express-4.17.1.tgz#abc"
  dependencies:
    body-parser "1.19.0"
    ms "2.0.0"

body-parser@1.19.0:
  version "1.19.0"
  resolved "https://registry.yarnpkg.com/body-parser/-/body-parser-1.19.0.tgz#def"
  dependencies:
    ms "2.0.0"

ms@2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/ms/-/ms-2.0.0.tgz#ghi"
`;

const BERRY = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 6

"express@npm:^4.17.1":
  version: 4.17.1
  resolution: "express@npm:4.17.1"
  dependencies:
    body-parser: 1.19.0
    ms: 2.0.0
  checksum: abc

"body-parser@npm:1.19.0":
  version: 1.19.0
  resolution: "body-parser@npm:1.19.0"
  dependencies:
    ms: 2.0.0
  checksum: def

"ms@npm:2.0.0":
  version: 2.0.0
  resolution: "ms@npm:2.0.0"
  checksum: ghi
`;

describe.each([
  ["classic", CLASSIC],
  ["berry", BERRY],
])("loadYarnLockGraph (%s)", (_label, contents) => {
  it("keeps every parent of a package reached through more than one route", () => {
    const { dir, lockPath } = writeLock(contents);
    try {
      const graph = loadYarnLockGraph(lockPath)!;
      const [msId] = graph.nodeIdsFor("ms", "2.0.0");

      // ms is pulled in by express directly and by body-parser. Deriving edges
      // from the capped display paths loses one of these on a real tree.
      expect([...graph.parentsFor(msId!)].sort()).toEqual([
        "body-parser@1.19.0",
        "express@4.17.1",
      ]);
    } finally {
      removeDir(dir);
    }
  });

  it("resolves a node id back to its name and version", () => {
    const { dir, lockPath } = writeLock(contents);
    try {
      const graph = loadYarnLockGraph(lockPath)!;

      expect(graph.getNode("body-parser@1.19.0")).toEqual({
        name: "body-parser",
        version: "1.19.0",
      });
    } finally {
      removeDir(dir);
    }
  });

  it("reports no parents for a package nothing depends on", () => {
    const { dir, lockPath } = writeLock(contents);
    try {
      const graph = loadYarnLockGraph(lockPath)!;
      const [expressId] = graph.nodeIdsFor("express", "4.17.1");

      expect(graph.parentsFor(expressId!)).toEqual([]);
    } finally {
      removeDir(dir);
    }
  });

  it("returns no node ids for a package absent from the lockfile", () => {
    const { dir, lockPath } = writeLock(contents);
    try {
      expect(loadYarnLockGraph(lockPath)!.nodeIdsFor("not-installed", "1.0.0")).toEqual([]);
    } finally {
      removeDir(dir);
    }
  });
});

describe("loadYarnLockGraph", () => {
  it("resolves a dependency declared by a range rather than by its version", () => {
    // Yarn keys entries by the requesting range, so the child's declared range
    // has to go through the selector map to find the entry it installs.
    const { dir, lockPath } = writeLock(`# yarn lockfile v1


parent@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/parent/-/parent-1.0.0.tgz#a"
  dependencies:
    child "^2.0.0"

child@^2.0.0:
  version "2.3.4"
  resolved "https://registry.yarnpkg.com/child/-/child-2.3.4.tgz#b"
`);
    try {
      const graph = loadYarnLockGraph(lockPath)!;
      const [childId] = graph.nodeIdsFor("child", "2.3.4");

      expect(childId).toBe("child@2.3.4");
      expect(graph.parentsFor(childId!)).toEqual(["parent@1.0.0"]);
    } finally {
      removeDir(dir);
    }
  });

  it("returns null for a lockfile with no usable entries", () => {
    const { dir, lockPath } = writeLock("# yarn lockfile v1\n\n");
    try {
      expect(loadYarnLockGraph(lockPath)).toBeNull();
    } finally {
      removeDir(dir);
    }
  });

  it("returns null for a file that cannot be read", () => {
    expect(loadYarnLockGraph("/nonexistent/yarn.lock")).toBeNull();
  });
});
